# A basic workflow to help you get started with actions

name: A Basic Workflow

# Contols when the workflow will run
on: 
  #Triggers the workfloe on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in 
# in paraallel
jobs:
  # This workflow contains a single job called "build"
  build-app:
  #The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  # Checks-out your reposity under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

  # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, World!
  # Runs a set of commands using the runnes shell
      - name: Run a multi-line script 
        run:
          echo test, and deploy your project/
          echo Add other actions to build,

  build-api:
    runs-on:  windows-latest
    steps:
      - run: echo "Building API"

  build-db:
    needs: build-api
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"

  package:
    needs: [ build-app, build-db ]
    runs-on: macos-latest
    steps:
      - run: echo "Hello Macos"







      